version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: editus-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - editus-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  redis:
    image: redis:latest
    container_name: editus-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - editus-network
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: editus-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
      DB_HOST: mysql
      REDIS_HOST: redis
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - editus-network
    volumes:
      - ./backend/logs:/app/logs
      # - ./backend/build/libs/web_ide-0.0.1-SNAPSHOT.jar:/app/app.jar

  jenkins:
    build:
      context: ./jenkins-docker
      dockerfile: Dockerfile
    container_name: jenkins-server
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    networks:
      - editus-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    environment:
      - JENKINS_OPTS=--httpPort=8080

volumes:
  mysql-data:
    driver: local
  jenkins_home:
    driver: local
  redis-data:
    driver: local

networks:
  editus-network:
    driver: bridge
