spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: editus-backend

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: "mySecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForSecurity123!"
  expiration: 86400000

logging:
  level:
    com.editus.backend: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

