spring:
  datasource:
    url: jdbc:mysql://editus-mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER:editus}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # spring boot 4 에서 사용

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:5173}

logging:
  level:
    com.editus.backend: DEBUG
